on:
  push:
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - if: steps.cache.outputs.cache-hit != 'true'
        run: |
          pip install sklearn
          pip install gensim
          pip install nltk
          pip install Elasticsearch
      - name: run tests
        run: python3 ./main.py
